---
title: "Stat139_Final_Project"
author: "Brice Laurent, Linh Vu, Aissata Bah"
date: "2023-11-30"
output: pdf_document
---

```{r library and data}
library(lme4)
library(ggplot2)
library(ggpubr)
library(lmtest)
library(sandwich)
library(knitr)

# load data
data_clean <- read.csv("data_clean.csv")

# subset to 2021 data only
data_clean_2021 = data_clean[data_clean$year == 2021,]
df = data_clean_2021
```


```{r corr}
# determine 1 representative variable from each of the 8 categories

# which(colnames(df) == "x1.1")
# which(colnames(df) == "x1.6")
f1 = cor(df[,39:44], use="na.or.complete")
f1
(colSums(f1) - 1)/(ncol(f1) - 1)

# which(colnames(df) == "x2.1")
# which(colnames(df) == "x2.4")
f2 = cor(df[,46:49], use="na.or.complete")
f2
(colSums(f2) - 1)/(ncol(f2) - 1)

# which(colnames(df) == "x3.1")
# which(colnames(df) == "x3.4")
f3 = cor(df[,51:54], use="na.or.complete")
f3
(colSums(f3) - 1)/(ncol(f3) - 1)

# which(colnames(df) == "x4.1")
# which(colnames(df) == "x4.8")
f4 = cor(df[,56:63], use="na.or.complete")
f4
(colSums(f4) - 1)/(ncol(f4) - 1)

# which(colnames(df) == "x5.1")
# which(colnames(df) == "x5.3")
f5 = cor(df[,65:67], use="na.or.complete")
f5
(colSums(f5) - 1)/(ncol(f5) - 1)

# which(colnames(df) == "x6.1")
# which(colnames(df) == "x6.5")
f6 = cor(df[,69:73], use="na.or.complete")
f6
(colSums(f6) - 1)/(ncol(f6) - 1)

# less correlation
# which(colnames(df) == "x7.1")
# which(colnames(df) == "x7.7")
f7 = cor(df[,75:81], use="na.or.complete")
f7
(colSums(f7) - 1)/(ncol(f7) - 1)

# which(colnames(df) == "x8.1")
# which(colnames(df) == "x8.6")
f8 = cor(df[,83:88], use="na.or.complete")
f8
(colSums(f8) - 1)/(ncol(f8) - 1)

#subset data and compute correlation on subset
cor(df[, c("x1.6", "x2.1", "x3.2", "x4.2", "x5.1", "x6.4", "x7.3", "x8.5")], use="na.or.complete")

#correlation with 2.1 removed
f.decide = cor(df[, c("x1.6", "x3.2", "x4.2", "x5.1", "x6.4", "x7.3", "x8.5")], use="na.or.complete")
(colSums(f.decide) - 1)/(ncol(f.decide) - 1)
```

```{r models using selected vars}
#subsetting df with selected variables
sub_df <- df[, c("country", "hdi", "Region", "x1.6", "x3.2", "x5.1", "x6.4","x7.3")]

#modelling distributions
f = ggplot(aes(hdi), data=sub_df) +
  geom_histogram(col="white") +
    labs(title="Distribution of HDI")

a = ggplot(aes(x1.6), data=sub_df) +
  geom_histogram(col="white") +
    labs(title="Distribution of 1.6")

b = ggplot(aes(x3.2), data=sub_df) +
  geom_histogram(col="white") +
    labs(title="Distribution of 3.2")

c = ggplot(aes(x5.1), data=sub_df) +
  geom_histogram(col="white") +
    labs(title="Distribution of 5.1")

d = ggplot(aes(x6.4), data=sub_df) +
  geom_histogram(col="white") +
    labs(title="Distribution of 6.4")

e = ggplot(aes(x7.3), data=sub_df) +
  geom_histogram(col="white") +
    labs(title="Distribution of 7.3")

ggarrange(f,a,b,c,d,e, ncol = 3, nrow = 3)

#fit models
sub_df$Region = factor(sub_df$Region, levels = c("EU + EFTA + North America", "East Asia & Pacific", "Eastern Europe & Central Asia", "Latin America & Caribbean", "Middle East & North Africa", "South Asia", "Sub-Saharan Africa")) #releveling region
summary(mod1 <- lm(hdi~x1.6 + x3.2 + x5.1 + x6.4 + x7.3 + Region, data = sub_df))
plot(mod1, c(1:3))
summary(mod4 <- lm(hdi^2~x1.6 + x3.2 + x5.1 + x6.4 + x7.3 + Region, data = sub_df))
plot(mod4, c(1:3))

#calculate robust standard errors for model coefficients
summary(mod4 <- lm(hdi^2~x1.6 + x3.2 + x5.1 + x6.4 + x7.3 + Region, data = sub_df))
robus = vcovHC(mod4, type = "HC")
sqrt(diag(robus))
coeftest(mod4, vcov = vcovHC(mod4, type = "HC"))
```

```{r pretty table}
summ = summary(mod1 <- lm(hdi~x1.6 + x3.2 + x5.1 + x6.4 + x7.3 + Region, data = sub_df))
kable(summ$coefficients)
```
