---
title: "PCA"
author: 
  - "Aissata Bah"
  - "Brice Laurent"
  - "Linh Vu"
date: "2023-12-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,message=F}
# Load Libraries
library(dplyr)
library(ggplot2)
library(lme4)
library(broom.mixed)
library(lmerTest)
library(tibble)
library(ggpubr)
library(knitr)

data = read.csv("./data/data_clean.csv")
```


```{r}
# Impute missing values with of values in the same region
selected_columns_pca = select(data, c(starts_with("x"), "region"))
selected_columns_pca = selected_columns_pca %>%
  rename(x8.7=x8.7..due.process.of.the.law.and.rights.of.the.accused)
selected_columns_pca_imputed = selected_columns_pca %>%
  group_by(region) %>%
  mutate_all(~ ifelse(is.na(.), mean(., na.rm = TRUE), .))
selected_columns_pca_imputed = selected_columns_pca_imputed[, -c(1,ncol(selected_columns_pca_imputed))]

# Extract Principle Components of Rule of Law Variables
pca = prcomp(selected_columns_pca_imputed, scale. = TRUE)
variance_explained = (pca$sdev^2) / sum(pca$sdev^2)
```


```{r}
# Visualize Principle Components
PC1and2 = as.data.frame(cbind(pca$x[,c(1,2)], data[, c("country", "year", "hdi")]))
PC1and2$PC1 = as.numeric(PC1and2$PC1)
PC1and2$PC2 = as.numeric(PC1and2$PC2)
PC1and2$Country = PC1and2$country
p1 = ggplot(data = PC1and2,aes(x=PC1, y=PC2)) + geom_point(aes(color = Country)) + theme(legend.text = element_blank(), legend.key.size = unit(2, 'mm')) + guides(color = guide_legend(ncol = 3)) + labs(title="PC2 versus PC1, by Country")
p2 = ggplot(data = PC1and2,aes(x=PC1, y=PC2)) + geom_point(aes(color = hdi)) + labs(title="PC2 versus PC1, by HDI")

p1
p2
```

\newpage

```{r}
# Fit mixed linear model with top 5 principal components
selected_columns_data = data[, c("country","year", "region", "hdi")]
selected_columns_data[selected_columns_data$year == "2012-2013", "year"] = "2012.5"
selected_columns_data[selected_columns_data$year == "2017-2018", "year"] = "2017.5"
selected_columns_data$year = as.numeric(selected_columns_data$year)
selected_columns_data$years_from_2000 = selected_columns_data$year - 2000
TopPCs = as.data.frame(cbind(pca$x[,seq(1,5)], selected_columns_data))
                  
lm = lm(hdi~years_from_2000+PC1+PC2+PC3+PC4+PC5+region,data=TopPCs)

kable(summary(lm)$coefficients)
```

```{r}
# Find significance of including region variable
lm_noRegion = lm(hdi~years_from_2000+PC1+PC2+PC3+PC4+PC5,data=TopPCs)

anova(lm, lm_noRegion)

```

```{r}
# Determine importance of each variable
TopPCs_loadings_abs <- abs(pca$rotation[,seq(1,5)])
TopPCs_loadings_abs_long <- as.data.frame(as.table(TopPCs_loadings_abs))
colnames(TopPCs_loadings_abs_long) <- c("Variable", "Principal_Component", "Loading")
ggplot(TopPCs_loadings_abs_long, aes(x = Principal_Component, y = Loading)) +
  geom_boxplot(outlier.size = 0) +
  geom_jitter(aes(color = Variable)) +
  labs(title = "Boxplot of Component Coefficients by Principal Component",
       x = "Principal Component",
       y = "Absolute Value of Component Coefficient")

rowSums(TopPCs_loadings_abs)[order(-rowSums(TopPCs_loadings_abs))]

TopPCs_loadings_abs_grouped = as.data.frame(TopPCs_loadings_abs) 
TopPCs_loadings_abs_grouped$Row_Labels = row.names(TopPCs_loadings_abs)
TopPCs_loadings_abs_grouped = TopPCs_loadings_abs_grouped %>%
  mutate(First_Digit = as.numeric(gsub("\\D*(\\d).*", "\\1", TopPCs_loadings_abs_grouped$Row_Labels))) %>%
  select(-Row_Labels)
TopPCs_loadings_abs_grouped = TopPCs_loadings_abs_grouped %>%
  group_by(First_Digit) %>%
  summarise(across(everything(), sum, na.rm = TRUE)) %>%
  column_to_rownames(var = "First_Digit")

TopPCs_loadings_abs_grouped = as.data.frame(t(TopPCs_loadings_abs_grouped)) %>% rename("1 (Constraints on Government Powers)" = "1", "2 (Absence of Corruption)" = "2", "3 (Open Government )" = "3", "4 (Fundamental Rights)" = "4", "5 (Order and Security)" = "5", "6(Regulatory Enforcement)" = "6", "7 (Civil Justice)" = "7", "8 (Criminal Justice)" = "8")

df = as.data.frame(colSums(TopPCs_loadings_abs_grouped)[order(-colSums(TopPCs_loadings_abs_grouped))])

names(df) = "Sum of Absolute Values of Component Coefficients"

kable(df)
```

```{r}
 lm_residuals = data.frame( "Residuals" = residuals(lm), "Fitted_Values" = fitted(lm))

fitted_resid = ggplot(data = lm_residuals, aes(x=Fitted_Values,y = Residuals)) + geom_point(color = "#1a84b8", alpha = 0.5) + geom_hline(yintercept=0)+ labs(title= "Residuals versus Fitted Values")

qq_resid = ggplot(lm_residuals, aes(sample = Residuals)) +
  geom_qq(color = "#1a84b8", alpha = 0.5) +
  geom_qq_line() +
  labs(title = "QQ Plot for Residuals",x = "Theoretical Quantiles (Standard Normal)", y = "Observed Quantiles (Residuals)")

ggarrange(fitted_resid,qq_resid, ncol = 2)
```